planets4/config/routes.rb
Planets4::Application.routes.draw do
  resources :satellites

  root "satellites#index"


end

planets4/app/models/satellite.rb
class Satellite < ActiveRecord::Base
	validates :name,{uniqueness: true, presence: true}
	
	has_many :children_satellites, class_name: 'Satellite', foreign_key: 'parent_id'
	belongs_to :parent_satellite, class_name: 'Satellite', foreign_key: 'parent_id'

end

planets4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

planets4/app/controllers/satellites_controller.rb
class SatellitesController < ApplicationController
  before_action :set_satellite, only: [:show, :edit, :update, :destroy]

  # GET /satellites
  # GET /satellites.json
  def index
    @satellites = Satellite.all
  end

  # GET /satellites/1
  # GET /satellites/1.json
  def show
  end

  # GET /satellites/new
  def new
    @satellite = Satellite.new
  end

  # GET /satellites/1/edit
  def edit
  end

  # POST /satellites
  # POST /satellites.json
  def create
    @satellite = Satellite.new(satellite_params)

    respond_to do |format|
      if @satellite.save
        format.html { redirect_to @satellite, notice: 'Satellite was successfully created.' }
        format.json { render action: 'show', status: :created, location: @satellite }
      else
        format.html { render action: 'new' }
        format.json { render json: @satellite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /satellites/1
  # PATCH/PUT /satellites/1.json
  def update
    respond_to do |format|
      if @satellite.update(satellite_params)
        format.html { redirect_to @satellite, notice: 'Satellite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @satellite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /satellites/1
  # DELETE /satellites/1.json
  def destroy
    @satellite.destroy
    respond_to do |format|
      format.html { redirect_to satellites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_satellite
      @satellite = Satellite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def satellite_params
      params.require(:satellite).permit(:name, :parent_id)
    end
end

planets4/app/helpers/application_helper.rb
module ApplicationHelper
end

planets4/app/helpers/satellites_helper.rb
module SatellitesHelper

	def get_children_satellites
		@children = Satellite.where( parent_id: params[:id] )
	end
	def get_parent 
		me = Satellite.find( params[:id] )
		if ! me.parent_id.nil?
			parent = Satellite.find( me.parent_id )
			parent.name
		else
			"No Parent"
		end

	rescue
		"Parent with id #{me.parent_id} has been deleted"
	end

end

planets4/app/views/layouts/application.html.erb
<html>
<head>
	<title>Satellites</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
	<style type="text/css">
		body {
		}
	</style>
</head>
<body>

<%= yield %>

</body>
</html>

planets4/app/views/satellites/_form.html.erb
<%= form_for @satellite do | f | %>
	
	<div class="field">

			<div class="field">
				<%= f.label :name %>
				<%= f.text_field :name %>
			</div>
			<div class="field">
				<%= f.label :parent_id %>
				<%= f.select :parent_id, Satellite.all.collect {| satellite | [satellite.name, satellite.id] }, { include_blank: true } %>
			</div>

			<div class="buttons">
				<%= f.submit %>
			</div>

	</div>
<% end %>

planets4/app/views/satellites/edit.html.erb
<h1>Edit</h1>

<%= render 'form' %>

<div class="buttons"><%= link_to 'Cancel', satellite_path %></div>

planets4/app/views/satellites/index.html.erb
<h1>Index Action</h1>



<ul id="main-list">
	<% @satellites.each do | satellite |  %>

		<li>
				<%= satellite.id %> - 
				<%= link_to satellite.name, satellite %>
				<%= link_to 'show', satellite %>
				<%= link_to 'edit', edit_satellite_path( satellite ) %>
				<%= link_to 'kill', satellite, method: :delete %>
		</li>

	<% end %>
</ul>

<h3><div class="buttons"><%= link_to 'Create new satellite', new_satellite_path %></div></h3>

planets4/app/views/satellites/new.html.erb
<h1>New</h1>

<%= render 'form' %>

<div class="buttons"><%= link_to 'Cancel', satellites_path %></div>

planets4/app/views/satellites/show.html.erb
<h1 style="color:green">Satellite Name: <%= @satellite.name %></h1>
<h2 style="color: red">Parent Satellite: <%= get_parent %></h2>
<h3 style="color: blue">Chillens</h3>
<% if !get_children_satellites.nil? %>
<ul>
	<% @children.each do |c| %>
	<li><%= link_to c.name, edit_satellite_path( c ) %></li>
	<% end %>
</ul>
<% end %>

<div class="buttons">
	<%= link_to 'Back', satellites_path %>
	<%= link_to 'Edit', edit_satellite_path %>
</div>