lab6/config/routes.rb
Lab6::Application.routes.draw do
  resources :episodes
  resources :series
  root 'series#index'

end

lab6/app/models/episode.rb
class Episode < ActiveRecord::Base
	validates :title, :description, :episode_number, { presence: true }
	validates :episode_number, { numericality: true }
	belongs_to :series
end

lab6/app/models/series.rb
class Series < ActiveRecord::Base
	validates :title, :start_date, :end_date, presence: true
	has_many :episodes
end

lab6/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lab6/app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
before_action :set_episode, only: [:edit, :show, :destroy, :update]


  def index
    @episodes = Episode.order(:episode_number)
  end

  def show
  end

  def new
    @episode = Episode.new
    respond_to do |format|
      format.js
      format.html
    end
  end

  def create
    @episode = Episode.new(episode_params)
    respond_to do |format|
      if @episode.save
        format.html { redirect_to episodes_path, notice: 'Episode was successfully created.' }
        format.json { render action: 'show', status: :created, location: @episode }
      else
        format.html { render action: 'new' }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_index_path, notice: "Episode #{@episode.episode_number} was deleted" }
    end
  end

  private

    def set_episode
        @episode = Episode.find(params[:id])
    end
    def episode_params
        params.require(:episode).permit(:title, :description, :episode_number, :series_id)
    end
end

lab6/app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to @series, notice: 'Series was successfully created.' }
        format.json { render action: 'show', status: :created, location: @series }
      else
        format.html { render action: 'new' }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:title, :start_date, :end_date)
    end
end

lab6/app/helpers/application_helper.rb
module ApplicationHelper
end

lab6/app/helpers/episodes_helper.rb
module EpisodesHelper

	def show_series_name
		
	end

end

lab6/app/helpers/series_helper.rb
module SeriesHelper
end

lab6/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lab6</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav id="top">
	<ul>
		<li><%= link_to 'Home', root_path %></li>
		<li><%= link_to 'Series', series_index_path %></li>
		<li><%= link_to 'Episodes', episodes_path %></li>
	</ul>
</nav>
	<header>
			<h1>Favorite TV Shows</h1>
	</header>
<article>
	<%= yield %>
</article>
</body>
</html>

lab6/app/views/series/_form.html.erb
<%= form_for(@series) do |f| %>
  <% if @series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% @series.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date, start_year: 2006 %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.date_select :end_date, start_year: 2006 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

lab6/app/views/series/edit.html.erb
<h1>Editing series</h1>

<%= render 'form' %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

lab6/app/views/series/index.html.erb
<h1>Listing series</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Episode Count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= series.title %></td>
        <td><%= series.start_date %></td>
        <td><%= series.end_date %></td>
        <td><%= series.episodes.count %></td>
        <td><%= link_to 'Show', series %></td>
        <td><%= link_to 'Edit', edit_series_path(series) %></td>
        <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series', new_series_path %>

lab6/app/views/series/new.html.erb
<h1>New series</h1>

<%= render 'form' %>

<%= link_to 'Back', series_index_path %>

lab6/app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @series.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @series.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @series.end_date %>
</p>

<div><strong>Episode Count:</strong> <%= @series.episodes.count %></div><br/>

<strong>Episodes</strong>
<ol>
<% @series.episodes.each do |e| %>
<li><%= link_to e.title, episode_path(e) %></li>
<% end %>
</ol>
<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>