lab2/config/routes.rb
Lab2::Application.routes.draw do
  get "user/index"
  get "user/create"
  get "user/update"
  get "user/delete"
  get "user/show"
  root :to => 'page#home'
  match '/about', to: 'page#about', via: 'get'
  match '/signup', to: 'page#signup', via: 'get'
  match '/login', to: 'page#login', via: 'get'

  resources :users

end

lab2/app/models/user.rb
class User < ActiveRecord::Base

	require 'digest/sha2'
	attr_accessor :password
	
	validates :username, :first_name, :last_name, { presence: true }
	validates :username, :email, { uniqueness: true }
	validates :password, { presence: true }
	validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "Invalid Email Address" }

	before_save :password
	before_save :generatecodes!

	def generatecodes! # acts upon object instead of returning result
		# Confirmation code
		if self.confirmation_code.nil?
			self.confirmation_code = Digest::SHA256.hexdigest( self.email + self.id.to_s )
		end
		# Cancelation code
		if self.cancelation_code.nil?
			self.cancelation_code = Digest::SHA256.hexdigest( self.username + self.email + self.id.to_s )
		end

	end

	def password= password

		if password.empty?
			"xxxxxxxxx"
		else
			false
		end

		# Salt
		self.password_salt = [Array.new( 6 ){rand( 256 ).chr}.join].pack( "m" ).chomp
		# Password Hash
		self.password_hash = Digest::SHA256.hexdigest( password + self.password_salt )
	end

	def self.authenticate username, password
		user = User.find_by_username username
		fromUser = Digest::SHA256.hexdigest( password + user.password_salt )
		if fromUser == user.password_hash
			return "Authenticated!!"
		else
			return "Username or password doesn't match. :-("
		end
	end

	def verify! conf_code
		user = User.find self.id
		if self.confirmation_code == conf_code 
			user.verified = true
			self.update_attributes(:verified => true)
			self.save
		 	"User: #{self.username} has been verified!"
		 	true
		else
			"The user could not be verified. User not in database?"
			false
		end
	end
	def self.cancel! user_id, can_code 
		user = User.find user_id
		if user.cancelation_code == can_code
			user.delete
			"#{user.username} has been deleted"
			true
		else
			"Wrong cancelation code! :("
			false
		end
	end
	
	def self.verified 
		User.where({verified:true})
	end
	# User.where({ name: "Joe", email: "joe@example.com" })

	# User.create username: "richard", eller", email: "richard@gurustu.co"
	# u1 = User.create username: "richard", first_name: "richard", last_name: "keller", email: "richard@gurustu.co"
	# u1 = User.create username: "Richardbenjamin", first_name: "Rick", last_name: "killer", email: "richard.be.jamin@gmail.com", password: "ez2rembr!@#"
end

lab2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lab2/app/controllers/page_controller.rb
class PageController < ApplicationController

  def home
  	@users = User.all
  end


  def about
  end

  def signup
  	@user = User.new
  end

  def login
  end
end

lab2/app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :set_user, only: [:update, :create, :show]
  def index
    @users = User.all
  end

  def create
  end

  def update
    
  end

  def delete
  end

  def show
  end

  def set_user
    @user = User.find(params[:id])
  end
end

lab2/app/helpers/application_helper.rb
module ApplicationHelper
end

lab2/app/helpers/page_helper.rb
module PageHelper
end

lab2/app/helpers/user_helper.rb
module UserHelper
end

lab2/app/views/page/_navigation.html.erb
<ul id="navigation">
	<li><%= link_to "Home", '/' %></li>
	<li><%= link_to "About", about_path %></li>
	<li><%= link_to "Sign Up", signup_path %></li>
	<li><%= link_to "Login", login_path %></li>
</ul>

lab2/app/views/page/about.html.erb
<h1>Page#about</h1>
<p>Find me in app/views/page/about.html.erb</p>

lab2/app/views/page/home.html.erb
<h2>List of users</h2>
<ol>
<% @users.each do |u| %>

	<li><%= u.username %></li>

<% end %>
</ol>

lab2/app/views/page/login.html.erb
<h1>Page#login</h1>
<p>Find me in app/views/page/login.html.erb</p>

lab2/app/views/page/signup.html.erb
<h1>Page#signup</h1>
<p>Find me in app/views/page/signup.html.erb</p>


<%= form_for @user do |f| %>

<div class="field">	
	<%= f.label :username %>
	<%= f.text_field :username %>
</div>
<div class="field">	
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
</div>
<div class="field">	
	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
</div>
<div class="field">	
	<%= f.label :email %>
	<%= f.text_field :email %>
</div>
<div class="field">	
	<%= f.label :password %>
	<%= f.password_field :password %>
</div>
<div class="field">	
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
</div>

<%= f.submit %>


<% end %>

lab2/app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

lab2/app/views/user/delete.html.erb
<h1>User#delete</h1>
<p>Find me in app/views/user/delete.html.erb</p>

lab2/app/views/user/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

lab2/app/views/user/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

lab2/app/views/user/update.html.erb
<%= form_for @user do |f| %>
	<%= f.text_field :username %>
	<%= f.submit %>
<% end %>